site_name: tonyfast
site_description:
site_url:
nav:
- readme: readme.md
- 07/10/21:
  - a lesson on testing notebooks for part 3 of the writers workshop:
    - testing-notebooks.md.ipynb: e7dd7ff3d808d57b77e9765626a73a91/testing-notebooks.md.ipynb
- 07/08/21:
  - copy and paste images and attachments directly into markdown cells:
    - copy-pasta-trick.ipynb: a9bb09cb019e201ed95b76a6f558a106/copy-pasta-trick.ipynb
- 07/03/21:
  - notebooks about IPython mimetypes and mediatypes:
    - all-the-displays.md.ipynb: 203fee00e29fadaaa0604e915eb7a8f6/all-the-displays.md.ipynb
    - mimemediatypes.md.ipynb: 203fee00e29fadaaa0604e915eb7a8f6/mimemediatypes.md.ipynb
    - readme.md: 203fee00e29fadaaa0604e915eb7a8f6/readme.md
- 07/01/21:
  - an essay on the inner and outside positions of computational notebooks with a practice exercise:
    - hyper-collage.ipynb: f53d109fffe1e46b90cd2da8ce322f45/hyper-collage.ipynb
- 06/07/21:
  - the utterances commenting system inside of the browser only jupyterlite interactive computing interface:
    - readme.md: 405e3ec4f800fbc9d2b0a142ef4d4b10/readme.md
    - utterance.ipynb: 405e3ec4f800fbc9d2b0a142ef4d4b10/utterance.ipynb
- 06/02/21:
  - notebooks with rdf metadata:
    - embed-rdf.ipynb: 16d3bc82d69890949212b46040bd86e1/embed-rdf.ipynb
- 04/30/21:
  - ? http://bl.ocks.org/tonyfast/raw/196c9aae8d51434c138722687e718364/?raw=true https://nbviewer.jupyter.org/gist/tonyfast/196c9aae8d51434c138722687e718364/details-summary.ipynb
    : - details-summary.ipynb: 196c9aae8d51434c138722687e718364/details-summary.ipynb
- 04/23/21:
  - A discussion about formal unit testing in notebooks:
    - 2021-testing-in-notebooks.ipynb: b617e4f87337a50e1361ab043b53c2c7/2021-testing-in-notebooks.ipynb
plugins:
- mkdocs-jupyter
docs_dir: tonyfast
site_dir: _build/html/mkdocs
